name: amap_map_fluttify
description: An `Amap` Map Component, Powered By `Fluttify` Compiler, A Dart Bindings Generator For Native SDK.
version: 1.10.0

environment:
  sdk: ">=2.6.0 <3.0.0"
  flutter: ">=1.12.13 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  amap_core_fluttify: ^0.15.0-dev.0
  amap_location_fluttify: ^0.21.0-dev.0
  amap_search_fluttify: ^0.17.0-dev.0
  url_launcher: ^6.0.9
  uni_map_platform_interface: ^0.6.0-dev.0
  foundation_fluttify: ^0.12.0-dev.1
  core_location_fluttify: ^0.7.0-dev.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.2

flutter:
  plugin:
    platforms:
      android:
        package: me.yohom.amap_map_fluttify
        pluginClass: AmapMapFluttifyPlugin
      ios:
        pluginClass: AmapMapFluttifyPlugin
  assets:
    - images/